### ISSUE TITLE
Can't change font size

### ISSUE THREAD

**Issue by GAumala** [FolioReader/FolioReader-Android#126]
I have a particular `.epub` file in which changing the font size value with the seek bar does update the `fontSize` in the `Config` class and trigger a rerender of `FolioPageFragment`, but the font size remains the same, no matter what. This bug only happens with this particular file, the ones provided in the sample app change the font size flawlessly. 

I'm not sure why does this happen. As far as I know, the `Config.fontSize` value sets one of these CSS classes to the `html` tag:

``` css
html.textSizeOne { font-size: 13px !important; }
html.textSizeTwo { font-size: 15px !important; }
html.textSizeThree { font-size: 17px !important; }
html.textSizeFour { font-size: 19px !important; }
html.textSizeFive { font-size: 21px !important; }
```

My `.epub` file has a bunch of `p` tags with the `normal` class which is defined like this:

``` css
.normal
{
font-size:small;
margin-top:0em;
margin-bottom:0em;
margin-left:0em;
margin-right:0em;
text-indent:0em;
text-align:justify;
font-weight:normal;
}
```

Could it be that this "normal" class has greater priority over the ones applied to the `html` tag? Any thoughts? The `.epub` file in question is copyrighted so I can't share it publicly.
