### ISSUE TITLE
table texts do not change 

### ISSUE THREAD

**Issue by csdal** [FolioReader/FolioReader-Android#149]
table tags do not inherit from html-set css rules.
<br/>
Solution: 
1. Add table css rules at FolioReader-Android > assets > css > Style.css.<br/>

```css
html.textSizeOne, table.textSizeOne { font-size: 13px !important; }
html.textSizeTwo, table.textSizeTwo{ font-size: 15px !important; }
html.textSizeThree, table.textSizeThree { font-size: 17px !important; }
html.textSizeFour, table.textSizeFour { font-size: 19px !important; }
html.textSizeFive, table.textSizeFive { font-size: 21px !important; }
```

2. Edit FolioReader > ui > base > HtmlUtil.java <br/>
```java
htmlContent = htmlContent.replace("<html ", "<html class=\"" + classes + "\" ");
htmlContent = htmlContent.replace("<table", "<table class=\""+classes+"\" ");
return htmlContent;```
